---
name: rule1
description: "Rule which sends an email when an email from 'test.nihilent.5375@gmail.com' is received"
pack: azure_vm_create
enabled: true
trigger:
  type: azure_vm_create.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: create vm
    type: contains
action:
  ref: azure_vm_create.vm_create
  parameters:
    Group_Name: '{{trigger.group}}'
    Location: '{{trigger.location}}'
    VM_Name: '{{trigger.vmname}}'